// <auto-generated />
using System;
using Blazor_Crud_Temp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Blazor_Crud_Temp.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Blazor_Crud_Temp.Shared.Entities.VideoGame", b =>
                {
                    b.Property<int>("_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("_id"));

                    b.Property<string>("Publisher")
                        .HasColumnType("text");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("_id");

                    b.ToTable("VideoGames");

                    b.HasData(
                        new
                        {
                            _id = 1,
                            Publisher = "Nintendo",
                            ReleaseYear = 2017,
                            Title = "The Legend of Zelda: Breath of The Wild"
                        },
                        new
                        {
                            _id = 2,
                            Publisher = "CD Projekt",
                            ReleaseYear = 2015,
                            Title = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            _id = 3,
                            Publisher = "Sega",
                            ReleaseYear = 2019,
                            Title = "Persona 5 Royal"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
